package de.tum.pom16.teamtba.reservationapp.activities;

/**
 * Created by evisa on 6/5/16.
 */
public enum IntentType {
    INTENT_SEARCH_RESULTS_TO_FILTER,
    INTENT_FILTER_TO_SEARCH_RESULTS,
    INTENT_SEARCH_TO_SEARCH_RESULTS,
    INTENT_TO_RESTAURANT_DETAILS,
    INTENT_NEAR_ME_TO_SEARCH_RESULTS,
    INTENT_DETAILS_TO_RESERVATION,
    INTENT_TIMESLOT_TO_SUCCESSFUL_RESERVATION,
    INTENT_DETAILS_TO_REVIEWS,
    INTENT_DETAILS_TO_REVIEWS_RESTAURANT_NAME,
    INTENT_DETAILS_TO_REVIEWS_AVERAGE_RATING,
    INTENT_DETAILS_TO_REVIEWS_NR_OF_REVIEWS
}
